### ISSUE TITLE
Internal VSCode command

### ISSUE THREAD

**Issue by EricCDI13** [ppatotski/vscode-commandbar#25]
Hi,
I've used your extension to call some arduino extension command, that's great, thanx.
I found the extension command arduino.xx in the contribution tab of extension description, that's not explain in your .md and not obvious for newbie in VSC like me.
I'd like o make a button to call an internal VSCode command like 'CTRL+SHIFT+P **Toggle Block Comment**'. Is there a way to do it ?
If yes, where we can find the VSC command code ?

**Comment by EricCDI13** [comment]
Ok I continue to investigate and found the answer. this 'palette' command is working : workbench.action.openWorkspaceSettings
To find command have a look to video.gif here : https://code.visualstudio.com/docs/getstarted/keybindings

Hope that give help to other newbies

**Comment by ppatotski** [comment]
Thanks Eric for feedback. Let me update documentation with this helpful information.

**Comment by ppatotski** [comment]
Updated documentation
