### ISSUE TITLE
Global settings, not per project

### ISSUE THREAD

**Issue by PixelT** [ppatotski/vscode-commandbar#28]
It's possible to create general settings for every project, not individually for each project?

**Comment by ppatotski** [comment]
Good idea. It should not be hard to add this feature. Likely, vscode has permission to save config file in user folder. Stay tuned.

**Comment by PixelT** [comment]
The best solution I think will be general (global) setting, which can be override individually in workspace (project) ;)

**Comment by ppatotski** [comment]
Yep. Also, it is going to work with no workspace opened.
