### ISSUE TITLE
Command depend on filetype

### ISSUE THREAD

**Issue by PixelT** [ppatotski/vscode-commandbar#30]
What do you think about functionality, where option can be (optionally) visible / hide based on type of file?
For example, some plugins / commands make sense / work only in specific language.
In settings I have a field, where I can provide in which languages this option should be visible / hide. If this field will be empty (or false), the option will be visible everywhere / always.

**Comment by ppatotski** [comment]
You are not the fist one who is requesting such functionality. Let me think about it.

**Comment by ffred** [comment]
"[commands](https://marketplace.visualstudio.com/items?itemName=fabiospampinato.vscode-commands)" extension from Fabio Spampinato has some filter options for doing that..

**Comment by ppatotski** [comment]
It is coming.
