### ISSUE TITLE
New type of command: Open file

### ISSUE THREAD

**Issue by PixelT** [ppatotski/vscode-commandbar#31]
I have some idea to add new type of command like 'Open file'
In this type of command I can provide path to file, which will be open in vscode editor.
Implementation example:
```
{
    ...
    "commandType": "file",
    "command": "~/Dropbox/my-file.md"
    ...
}
```
Example of use:
There isn't exist any plugin for vscode to manage notes like [atom-notes for atom](https://github.com/lexicalunit/atom-notes) or [PlainNotes for sublimetext](https://github.com/aziz/PlainNotes).
By this type of command I can simulate in some degree the operation of such a plugins that I listed above. I can create file (for example on dropbox, with *.md extension) which will have notes or todos and open it on vscode no matter in which project / workspace currently I am.
What do you think about something like that? :)

**Comment by ppatotski** [comment]
I can see that. `"commandType"` could be "files". `"command"` in this case could be a comma-separated list of paths that will show up as a dropdown in palette. Single entry will open file instantly. Make sense?

**Comment by PixelT** [comment]
Yeah that also will be great! And I only want to add, that when the `"command"` have only one file in list, then the file will be automatically open instead of dropdown with this one item ;)

**Comment by PixelT** [comment]
And I can see the second usage of it - because extension support workspace settings, it can be use to "mark" files as favorite and rapid access to them 😍

**Comment by PixelT** [comment]
Works great, thank for your work!
