### ISSUE TITLE
set command text according to an environment variable ?

### ISSUE THREAD

**Issue by ffred** [ppatotski/vscode-commandbar#36]
Hi, thanks for your work.
just beginning with VSCODE to develop with Golang and was looking to create some kind of switch command or be able to set a command text (and/or tooltip or color eventually) according to an environment variable or something I could set in VSCODE maybe..?
some way to have a command that could also be some kind of flag.
do you think something like that could be possible...?
thanks
Fred

[edit:] forgot to mention that I'm working on Windows. and I know that if the text is set according to an environment variable, VSCODE probably won't refresh it before I relaunch it again if I change that environment variable during a VSCODE session.. not a real problem for me, but maybe the best option would be to be able to change the text programmatically inside VSCODE, not necessarily directly according to an environment variable.

**Comment by ppatotski** [comment]
Thank you! Well. Are you referring to system/user environment variable such as 'PATH'?
You could have a command (aka shortcut) that prints system information or something to 'OUTPUT'. Not sure I understand your case.

**Comment by ffred** [comment]
sorry if I'm not clear. yes I was referring to system/user environment variable, but after a little more thinking, it's not necessary to set that according to an environment variable. 
what I'd like to have is a way to have some kind of "switch button". for example it's start text value could be "SET" and after I click on it and launch my external command it will switch to "UNSET" text, according to a value set somewhere, was it an environment variable or not.
and it could also be a change of color, not necessarily of the text. just to have some king of visual flag of an external setting.
but of course I'd understand if that's something not doable or too far from the actual use of vscode-commandbar. 
thanks.

**Comment by ffred** [comment]
Hi,
just made another simple command to show the value in the terminal as you said and will go with that for now.
of course if there's a way someday to change a command text/color programmatically, I will still be interested, but will do it like that for now..
thanks.

**Comment by ffred** [comment]
sorry, don't want to bother continually, but while trying to create other commands I looked again at the commandbar extension webpage to find documentation and while looking at your animated demo.gif, I saw that the commandbar button "Serve Polymer UI" just change when you click on it to "Serve Polymer UI (in progress)". so it seems possible to change a button text value "programmatically" ?
sorry if I misunderstood the way it work, I'm new to VSCODE, but can you tell me why/how the text is changing in this animated gif.
thanks..
Fred

**Comment by ppatotski** [comment]
It is possible to change text programmatically. Demo video shows that command switched to 'wait for command to complete' state which is under control of commandbar extension.
Switch behavior is not something hard to add to command. However, I am concerned about stability and reliability of that functionality: what if state will fail to change or will be changed externally - that will make command state out of sync.

**Comment by ffred** [comment]
well, my purpose is just to make something simple. let say I have a button witch start to "ON" value. if I click on it it will launch a simple bat file and set it's text value to "OFF". and it will revert if I click again..
no worry about out of sync in my case, but I understand that it could be with special uses.. but we're here to make programs with the less possible bugs, so we also have to be careful with how we use our tools.

**Comment by ppatotski** [comment]
Thanks for understanding.
