### ISSUE TITLE
Execute VSCode command with an argument

### ISSUE THREAD

**Issue by Eccenux** [ppatotski/vscode-commandbar#48]
Some commands can take extra args. Would be useful to be able to e.g. run tests:
```js
vscode.commands.executeCommand("workbench.action.tasks.runTask", "Run tests")
```
This runs task with label "Run tests".

To keep your current syntax you could add colons to separate arguments like so:
```js
"command": "workbench.action.tasks.runTask:Run tests",
```

And then just change your `executeNext` like so:
```js
const executeNext = function executeNext(palettes, index) {
	let vscommand = palettes[index];
	let args = [];
	if (vscommand.indexOf(':') < 0) {
		args = [vscommand];
	} else {
		args = vscommand.split(':');
	}
	vscode.commands.executeCommand.apply(vscode.commands, args).then(() => {
		//...
```

I've tested above and it works :-).

Note that this way you could only pass string arguments to commands. And the arguments couldn't contain semicolons... But I don't think that would be a real problem.

**Comment by ppatotski** [comment]
This feature is coming soon
