### ISSUE TITLE
Some of octicons icon doesn't work

### ISSUE THREAD

**Issue by PixelT** [ppatotski/vscode-commandbar#50]
For example:
```
"text": "$(file) some text",
"text": "$(note) some text"
```

**Comment by ppatotski** [comment]
It is probably support icons up to certain version. Try this `"${file-text} some text"` instead

**Comment by lonix1** [comment]
`$(octicon-database)` doesn't work.

Does this feature need me to install icons or something?

**Comment by ppatotski** [comment]
Try $(database)
