### ISSUE TITLE
Possibility to set label when type = file

### ISSUE THREAD

**Issue by PixelT** [ppatotski/vscode-commandbar#51]
now we can define list of files / urls like this:

```
"command": [http://devdocs.io,http://github.com]
```

and when I click I will have an item list:

```
http://devdocs.io
http://github.com
```

It's possible to define a label for item, for example:
http://devdocs.io -> label: devdocs
http://github.com -> label: github
then the list will be look like:

```
devdocs
github
```

Edit: maybe something like this:
```
"command": [http://devdocs.io:devcods page label example,http://github.com:github page]
```

**Comment by ppatotski** [comment]
`:` will not work as a separator in our case. We can try `|`. Let me think about it.

**Comment by ppatotski** [comment]
Resolved with #57

**Comment by PixelT** [comment]
Works perfectly, thanks!

**Comment by PixelT** [comment]
But unfortunately I found another bug here:
```
        {
            "text": "Notes",
            "tooltip": "Notes",
            "color": "#eee",
            "commandType": "file",
            "command": "~/Dropbox/VSNotes/music.md"
        },
```
When I click on it, I get an error:

`Running the contributed command:'extension.commandbar.command_13' failed.`
