### ISSUE TITLE
Hard to work with multi-root workspaces and executing commands in context of active workspace root

### ISSUE THREAD

**Issue by darkvertex** [ppatotski/vscode-commandbar#52]
Hello,

Love the idea of the extension and the ease of use, but I am struggling to make it work for my needs.

I have a multi-root workspace, so multiple folders. When I click a CommandBar button with a custom command, I need that command to run from the working directory of the active open file.

Either that, or present me from which workspace root I'd like to run the command. In other words, something equivalent to "cd" into the folder and then executing my commandline.

At the moment the commands I need to run all fail because of this, and I don't want to hardcode the paths into them, because it's the same exact command for every folder in my project so I don't want a button per folder, I want a button per command.

Am I making sense? With native VSCode "Tasks" I can use "$workspaceFolder" to represent the current workspace folder (in a multi-root workspace) to make things a bit more generic, but I don't get the shiny button your nice extension provides. :)

**Comment by ppatotski** [comment]
Thanks for feedback. I am trying to find some time to finish multi-workspace feature support. Let me also check possibility of executing a Task from a command. Stay tuned.

**Comment by ppatotski** [comment]
Try latest version. See if using a mix of Tasks and Commands can work for you command support
> `palette`: executes any vscode command or any extension command
> - comma-separated list of commands that get executed sequentially
> - command support arguments separated by pipe (e.g. `workbench.action.tasks.runTask|My Task`)

**Comment by ppatotski** [comment]
@darkvertex I added multi-folder workspace handling. Please let me know your feedback.
