### ISSUE TITLE
wrong commandbar.json location

### ISSUE THREAD

**Issue by cengizhan** [ppatotski/vscode-commandbar#55]
why is this file not in vscode data folder but in my drive d? (i have installed vscode to drive d)

it seems that file location is hard coded to the <installation-drive>/users/user-name/commandbar.json

**Comment by ppatotski** [comment]
There are two commandbar.json config files. One of them is global and should be stored in user home folder. The other one in currently opened workspace (e.g. `my-app/.vscode/commandbar.json`)

**Comment by cengizhan** [comment]
my user folder is c:\users\ because my system drive is c. but that global one is in d:\users

**Comment by ppatotski** [comment]
Can you check PATH in environments please? Here is how I am getting user folder: `process.env.HOME || process.env.HOMEPATH || process.env.USERPROFILE`

**Comment by ppatotski** [comment]
@cengizhan, can you check the latest version please?

**Comment by cengizhan** [comment]
does not work. i have selected "create global settings" and this notification is shown

> A system error occurred (UNKNOWN: unknown error, mkdir '\\Users\cengiz\.vscode')

**Comment by ppatotski** [comment]
@cengizhan please check if the latest version fixes this issue.

**Comment by ppatotski** [comment]
I did not find the way to get user data folder path properly with vscode api.
