### ISSUE TITLE
Global Variables

### ISSUE THREAD

**Issue by EmbedEngineer** [ppatotski/vscode-commandbar#56]
Possibility to enter global variables like in the "normal" tasks e.g. ${workspaceFolder} or ${file} and it would be also great to be able to define your own variables.

**Comment by ppatotski** [comment]
Can you please elaborate more on "define your own variables"?

**Comment by EmbedEngineer** [comment]
Sure, I have something like this in my mind:
`"Varibales": [
  {
    "Name": "myvar",
    "Value": "parameter1"
  },
.
.
.
   "command": "run test ${variables.myvar}"`

I don't know if this is possible at all, but if it is, it would be great to have it.

And of course thank you for your good work and please keep up doing it. I do really like command bar.

**Comment by ppatotski** [comment]
Thanks for feedback. Global variable handling is in progress and will be ready soon. As per defining own variables I need to think about it. I need probably to see more stronger case before I decide to commit to that functionality.
