### ISSUE TITLE
Single item doesn't work

### ISSUE THREAD

**Issue by PixelT** [ppatotski/vscode-commandbar#59]
As I wrote here:
https://github.com/ppatotski/vscode-commandbar/issues/51#issuecomment-384514587

Multiple items works, but single item doesn't:
```       
 {
    "text": "Notes",
    "tooltip": "Notes",
    "color": "#eee",
    "commandType": "file",
    "command": "~/Dropbox/VSNotes/notes.md"
},
```
When I click on it, I get an error:
```
Running the contributed command:'extension.commandbar.command_13' failed.
```

**Comment by ppatotski** [comment]
ah, got it, I will fix it soon, thanks.
