### ISSUE TITLE
How to run an extention command

### ISSUE THREAD

**Issue by theadin** [ppatotski/vscode-commandbar#75]
HI,
I was just wondering what I put in the "Command" parameter to run an extension command. 

Just as an example. I downloaded the "Bookmarks" extension. To use it you can for example choose "Bookmarks: Toggle" from the Command Palette or use the shortcut ctrl+alt+k.
So what would I put in "Command:" in commandbar.json?

**Comment by ppatotski** [comment]
You can find a list of commends in https://github.com/alefragnani/vscode-bookmarks/blob/master/package.json file. In your case it can be 'bookmarks.toggle'.

**Comment by theadin** [comment]
ok. Thanks 👍
