### ISSUE TITLE
The extension does not see/load commandbar.json configuration from opened project (after upgrade to 0.3.0)

### ISSUE THREAD

**Issue by yegor-mialyk** [ppatotski/vscode-commandbar#77]
Just upgraded to 0.3.0 and my command disappeared from the command bar. Looks like the extension does not see my commandbar.json under .vscode folder.

My project opened through Open Folder (no any workspaces yet). A previous version (0.2.x) worked fine but now it does not.

========
Version: 1.31.1 (user setup)
Commit: 1b8e8302e405050205e69b59abb3559592bb9e60
Date: 2019-02-12T02:20:54.427Z
Electron: 3.1.2
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17763

**Comment by ppatotski** [comment]
I cannot reproduce it on mac. Do you have global commandbar.json as well?

**Comment by ppatotski** [comment]
Can you see any error in logs (`cmd-shift-p` -> Search `Show Logs` -> `Extension Host`) ?

**Comment by yegor-mialyk** [comment]
I do not have any global commandbar.json. The log is clean, no errors:

[2019-02-22 12:42:05.703] [exthost] [info] ExtensionService#_doActivateExtension gsppvo.vscode-commandbar {"startup":true,"activationEvent":"*"}
[2019-02-22 12:42:05.703] [exthost] [info] ExtensionService#loadCommonJSModule C:\Users\Yegor\.vscode\extensions\gsppvo.vscode-commandbar-0.3.0\extension

**Comment by yegor-mialyk** [comment]
OK, found the issue:
`getWorkspaceFolder()` return my folder under Windows as:

> /d:/Local/MY/far-plugins

@ppatotski, do you see this extra slash in the beginning?

If I remove it (for instance, like this: `return folder.substring(1)`), everything works fine.

**Comment by ppatotski** [comment]
I think I used wrong property to extract path from uri. I published another version with the fix. Can you please check? Thanks for quick responses!

**Comment by yegor-mialyk** [comment]
Works fine now (0.3.1). Thank you!
